[package]
name = "relltee"
version = "0.2.2"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = "thin"

[dependencies]
itertools = "0.10.0"
structopt = "0.3.15"
indicatif = "0.15"
serde = "1.0"
serde_tuple = "0.5"
serde_json = "1.0"
csv = "1.1"
hashbrown = "0.9.1"
rand = "0.7"
rand_pcg = "0.2"
rand_distr = "0.2"
cty = "0.2.1"

[build-dependencies]
cc = "1.0"
sleef-shim = { git = "https://github.com/zachmatson/sleef-shim-rs", branch = "main" }

[target.'cfg(all(target_arch = "x86_64", target_feature = "avx2"))'.build-dependencies]
sleef-shim = { git = "https://github.com/zachmatson/sleef-shim-rs", branch = "main", features = ["build-sleef"] }
