[package]
name = "relltee"
version = "0.2.2"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = "thin"

[features]
sleef = ["sleef-sys"]

[dependencies]
structopt = "0.3.15"
indicatif = "0.15"
serde = "1.0"
serde_tuple = "0.5"
serde_json = "1.0"
csv = "1.1"
hashbrown = "0.9.1"
rand = "0.7"
rand_pcg = "0.2"
rand_distr = "0.2"
sleef-sys = { git = "https://github.com/zachmatson/sleef-sys/", rev = "a13688c", optional = true }
cfg-if = "1.0.0"