[package]
name = "steps_adapter"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "WASM adapter exposing the STEPS simulation to the web portal"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
console_error_panic_hook = "0.1"
create_typescript_interface = { path = "./create_typescript_interface" }
js-sys = "0.3.57"
serde = "1.0"
serde-wasm-bindgen = "0.4.3"
steps_core = { path = "../core" }
web-sys = { version = "0.3", features = ["Blob", "Url"] }
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
