on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build_and_deploy:
    name: Build and Deploy to Cloudflare Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          default: true
      - uses: jetli/wasm-pack-action@v0.4.0
      - run: |
          cd portal
          npm ci
          npm run build
      - uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages publish portal/build/dist --project-name="steps-portal"
